# Packages installed with conda
#   To create environment:  conda env create --file environment.yml

name: hep-env
channels:
  - conda-forge
  - defaults
dependencies:
  - awkward
  - cython
  - h5py
  - ipywidgets
  - julia=1.0.3
  - jupyterlab=2.2.4
  - line_profiler
  - lmfit
  - matplotlib
  - memory_profiler
  - mpmath
  - multiprocess
  - nodejs=13.12.0
  - numba
  - numericalunits
  - numexpr
  - numpy
  - pandas
  - paramiko
  - pip
  # - pip:
  #   - awkward1
  #   - uproot4
  - python=3.7.6
  - root=6.18.04
  - root_numpy
  - scipy
  - scikit-learn
  - sympy
  - tqdm
  - uncertainties
  - uproot